var popCtx={groupTagsDict:{}},username,inResearchMode=false,ac,GlobalData=null;function sendMessage(a){window.parent.postMessage(a,"*")}chrome.runtime.sendMessage({name:"initialData"},function(a){GlobalData=a.globalData;initBookmarkWindow();sendMessage({type:"ifbookmark"})});window.addEventListener("message",receiveMessage,false);
function receiveMessage(a){a=a.data;switch(a.type){case "sendCtx":popCtx=$.extend(popCtx,a.data);objectToform(popCtx);break;case "sendRetags":showTags("recommended",a.data);break;case "updateGroupTag":popCtx.groupTagsDict=a.data;a=$("#diigobm-group").find(".content").attr("data-id");showTags("group",popCtx.groupTagsDict[a]);break}}$("#tag-edit").on("click",function(){chrome.tabs.create({url:"https://www.diigo.com/cloud/"+username})});$("#remove").on("click",function(){sendMessage({type:"qdeletebookmark"})});
$("#show-url").on("click",function(){$("#diigobm-url-input").toggle()}).Gtooltip({position:"top"});$("#tag-cloud-icon").on("click",function(){$("#tag-cloud").toggle()}).Gtooltip({positon:"top"});function triggerEvent(a,c){var d=new Event(c);a.dispatchEvent||(a=a[0]);a.dispatchEvent(d)}function inList(a){return some(popCtx.bm.lists,function(c){return c.id==a})}function inOutliner(a){return some(popCtx.bm.outliners,function(c){return c.id==a})}
function inGroup(a){return some(popCtx.bm.groups,function(c){return c.name==a})}function toggleTag(a,c){var d=$("#diigobm-tag-input"),e=ParseTags.parseTags(d.val(),true),g=$.inArray(a,e);if(c===undefined)g>=0?e.splice(g,1):e.push(a);else if(c)g==-1&&e.push(a);else g>=0&&e.splice(g,1);e=ParseTags.unparseTags(e);if(e.length)e+=" ";d.val(e);placeCursorAtLast(d[0]);updateTagStatus()}
function updateTagStatus(){var a=$("#diigobm-tag-input"),c=ParseTags.parseTags(a.val(),true);$("#tag-cloud-container").find(".Diigo-Bookmark-Tag-item").each(function(){var d=$(this),e=d.text();$.inArray(e,c)!=-1?d.addClass("selected"):d.removeClass("selected")});$("#diigobm-recent-tag, #diigobm-recommend-tag, #diigobm-group-tag").find(".diigo-tag").each(function(){var d=$(this),e=d.text();$.inArray(e,c)!=-1?d.addClass("selected"):d.removeClass("selected")})}
function placeCursorAtLast(a){var c=a.value.length;setTimeout(function(){placeInputCursor(a,c)},13)}function placeInputCursor(a,c){a.focus();if(a.createTextRange){var d=a.createTextRange();d.move("character",c);d.select()}else if(a.selectionStart>=0){a.focus();a.setSelectionRange(c,c)}}
function showTags(a,c){if(a=="recommended"){c=c.filter(function(f){return $.inArray(f,popCtx.mytag)>=0});c=popCtx.lastUsedTags.concat(c);if(c.length==0)return;else $("#diigobm-recommend-tag").show()}for(var d=document.createDocumentFragment(),e=0;e<c.length;e++){var g=document.createElement("div");g.className="diigo-tag";g.innerText=c[e];$(g).toggleClass("selected",$.inArray(c[e],popCtx.bm.tags)>=0);d.appendChild(g)}if(a=="recommended")$(d).appendTo($("#diigobm-recommend-tag"));else if(a=="group"){$("#diigobm-group-tag").find(".loading").hide();
$("#diigobm-group-tag").find(".diigo-tag").remove();$(d).appendTo($("#diigobm-group-tag"))}}function isURL(a){return/^(https|http|ftp|rtsp|mms)+:\/\//.test(a)?true:false}
function formToObject(){var a=true,c=$("#diigobm-url-input").val();if($("#diigobm-title-input").val().match(/^\s*$/)){a=false;$("#diigobm-title").find(".diigo-alert-tip").show()}if(!isURL(c)||c.match(/^\s*$/))if(a==true){a=false;$("#diigobm-url").find(".diigo-alert-tip").show()}if(a!=false){a={};a.title=$("#diigobm-title-input").val();if(a.title.match(/^\s*$/))a.title=popCtx.bm.title;a.url=$("#diigobm-url-input").val();if(a.url.match(/^\s*$/)||!isURL(a.url))a.url=popCtx.bm.url;a.description=$("#diigobm-des-input").val();
a.tags=ParseTags.parseTags($("#diigobm-tag-input").val(),true);a.mode=$("#op-private").prop("checked")?2:0;a.unread=$("#op-readlater").prop("checked")?true:false;c=$("#diigobm-list").find(".content").attr("data-id");a.shareLists=c?[c]:[];c=$("#diigobm-group").find(".content").attr("data-id");a.shareGroups=c?[c]:[];a.shareAnnotations=$("#Diigo-Bookmark-checkShareExisting").find(".op-checkbox-container").hasClass("checked")?true:false;a.cache=$("#op-cache").prop("checked")?true:false;chrome.runtime.sendMessage({name:"saveBookmarkFromBookmarkWin",
data:{url:a.url,mode:a.mode,title:a.title,tags:a.tags,description:a.description,unread:a.unread,urlId:popCtx.bm.urlId,cache:a.cache,groups:a.shareGroups,shareExistingAnnotations:a.shareAnnotations,lists:a.shareLists}});setTimeout(function(){sendMessage({type:"closeWin"})},500)}}
function getTagScale(a){var c=[];a.sort(function(b,h){return b.count<=h.count?1:-1});a=a.slice(0,101);var d=a[0].count,e=a.length;a.sort(function(b,h){return b.name.toLowerCase()<=h.name.toLowerCase()?-1:1});for(var g=0;g<e;g++)c[g]=a[g].count;c=arrayUnique(c);e=c.length;c.sort(function(b,h){return b<h?1:-1});var f=Math.ceil(e/10);e=c.slice(1,1+f);g=c.slice(1+f,1+2*f);c=c.slice(1+2*f,1+3*f);return{topTags:a,maxCount:d,first:e,second:g,third:c}}
function updateBookmark(a){if(inResearchMode!==true)if(a.generated==true){var c=a.bm;a.unread===true&&$("#read-later").addClass("unread").text("Mark as Read");$("#onload").hide();if(c.saved==true){$("#remove").show();$("#remove").attr("data-gtooltip","Saved "+c.datetime+". Click to remove");$("#bookmark-save").text("Edit").addClass("saved");$("#cached").show().unbind("click").bind("click",function(){getSelectedTab(function(d){var e="https://www.diigo.com/cached?url="+encodeURIComponent(d.url);chrome.tabs.create({url:e,
index:d.index+1})})})}if(c!=undefined){$("#diigobm-title-input").val(c.title).trigger("input");triggerEvent($("#diigobm-title-input"),"change");$("#diigobm-url-input").val(c.url)}else{$("#diigobm-title-input").val(window.parent.document.title);$("#diigobm-url-input").val(tab.url)}c.mode==2&&$("#op-private").prop("checked",true);c.unread==true&&$("#op-readlater").prop("checked",true);a=ParseTags.unparseTags(c.tags);blank(a)||$("#diigobm-tag-input").val(a+" ")}}
function initBookmarkWindow(a){$("#research-mode-notification").hide();if(a){$("#top-bar").find("span").text("Focused Research").end().find("div").hide();$("#diigobm-title,#diigobm-url,#op-cache,#diigobm-recommend-tag").hide();chrome.storage.local.get("isShowResearchTip",function(b){if(typeof b.isShowResearchTip==="undefined"||b.isShowResearchTip!=false)$("#research-mode-notification").show()});$("#research-mode-close-notify").on("click",function(){$("#research-mode-notification").hide();chrome.storage.local.set({isShowResearhTip:false})})}a=
navigator.userAgent.toLowerCase();var c=a.indexOf("macintosh")!=-1||a.indexOf("mac os x")!=-1;if(c){$("#diigobm-url").addClass("mac");$("#list-group select").css("text-indent","7px")}else $("#diigobm-url").addClass("win");$("#link-icon").on("click",function(){var b=$("#diigobm-url");if(c)b.toggleClass("mac-unfold");else b.hasClass("unfold")?b.addClass("fold").removeClass("unfold"):b.addClass("unfold").removeClass("fold")});autoTextarea.init(document.getElementById("diigobm-title-input"),40);autoTextarea.init(document.getElementById("diigobm-des-input"),
80);$("#diigobm-tag-dropdown").on("click",function(){$(this).toggleClass("cloud");if($("#tag-cloud").css("display")=="none"){$("#tag-suggestion").hide();$("#tag-cloud").show()}else{$("#tag-suggestion").show();$("#tag-cloud").hide()}});$("#diigobm-recent-tag").on("click","a",function(){$("#diigobm-recent-tag").find(".diigo-tag").each(function(){toggleTag($(this).addClass("selected").text(),true)})});$("#diigobm-options,#Diigo-Bookmark-checkShareExisting").on("click",".op-checkbox-container",function(){$(this).toggleClass("checked")});
$("#bm-main").on("keydown",function(b){if(b.keyCode==13){if(b.target.tagName.toLowerCase()!="textarea"||b.ctrlKey)formToObject()}else b.keyCode==27&&window.close()});$("#op-cache").find(".op-checkbox-container").removeClass("checked");$("#remove").Gtooltip();$("#close").Gtooltip().on("click",function(){sendMessage({type:"closeWin"})});a=[];var d=popCtx.myTagsWithCount?popCtx.myTagsWithCount:GlobalData.myTagsWithCount;d.sort(function(b,h){return b.count<=h.count?1:-1});for(var e=d.length,g=0;g<e;g++)a[g]=
d[g].name;a={resultsClass:"diigolet ac_results",data:a,mode:"multiple",multipleSeparator:" ,",id:"diigolet-ac"};try{new AutoComplete("#diigobm-tag-input",a)}catch(f){debug(f)}$("#diigobm-tag-input").bind("input",function(){updateTagStatus()});$("#diigobm-list-addInput").on("focus",function(){$("#diigobm-list-add .diigo-alert-tip").hide()});$("#close-upgrade-info").on("click",function(){$("#upgrade-info").hide()});$("#diigobm-list-addBtn").on("click",function(){if(!$(this).parent().hasClass("processing"))if(GlobalData.permissions.createOutliner){var b=
$("#diigobm-list-addInput").val(),h=$("#diigobm-list-add .diigo-alert-tip"),i=[],k=popCtx.lists.length,j;for(j=0;j<k;j++)i.push(popCtx.lists[j].title);if(b.match(/^\s*$/)){h.show().find("span").text("Input a name");$("#diigobm-list-addInput").focus()}else if($.inArray(b,i)!==-1)h.show().find("span").text("Name existed !");else{$(this).parent().addClass("processing");getSelectedTab(function(l){chrome.tabs.sendMessage(l.id,{name:"createList",data:b})})}}else $("#upgrade-info").show()});$("#diigobm-list-addCancel").on("click",
function(){$("#diigobm-list-add .diigo-alert-tip").hide();$("#diigobm-list-add").hide();$("#diigobm-list").show();$("#diigobm-list-addInput").val("")});$("#w-upgrade").on("click",function(b){b.preventDefault();googleEvent("Chrome extension","Click upgrade from outliner creation","outliner");chrome.tabs.create({url:"https://www.diigo.com/premium?f=outliner"});$("#diigobm-list-add-tip").hide();$("#diigobm-list").show()});$("#w-cancel").on("click",function(b){b.preventDefault();$("#diigobm-list-add-tip").hide();
$("#diigobm-list").show()});$("#diigobm-recent-tag,#diigobm-recommend-tag,#diigobm-group-tag").on("click","div",function(b){/diigo\-tag/.test(b.target.className)&&toggleTag($(this).text())});$("#bottom").on("click",function(b){switch(b.target.id){case "diigobm-saveBtn":formToObject();break;case "diigobm-cancelBtn":window.close();break}});$("#diigobm-tag-input").focus();$("#refresh-outliner,#refresh-group").on("click",function(){$(this).addClass("processing");getSelectedTab(function(b){chrome.tabs.sendMessage(b.id,
{name:"refreshMyStuff"})})})}
function objectToform(a){var c=a.bm;a.generated===true&&$("#onload").hide();if(c.saved==true){$("#remove").show();$("#top-bar").find(".top-bar-title").text("Edit bookmark")}$("#remove").attr("data-gtooltip","Saved "+c.datetime+". Click to remove");if(c!=undefined){$("#diigobm-title-input").val(c.title);triggerEvent($("#diigobm-title-input"),"change");$("#diigobm-url-input").val(c.url)}else chrome.tabs.getSelected(function(e){$("#diigobm-title-input").val(e.title);triggerEvent($("#diigobm-title-input"),"change");
$("#diigobm-url-input").val(e.url)});c.mode==2&&$("#op-private").prop("checked",true);c.saved==false&&localStorage["prefs.bookmark.privateByDefault"]=="true"&&$("#op-private").prop("checked",true);c.unread==true&&$("#op-readlater").prop("checked",true);if(c.description.length>0){$("#diigobm-des-input").text(c.description).trigger("change");triggerEvent($("#diigobm-des-input"),"change")}else if(a.selection){$("#diigobm-des-input").text('"'+a.selection+'"');triggerEvent($("#diigobm-des-input"),"change")}var d=
ParseTags.unparseTags(c.tags);blank(d)||$("#diigobm-tag-input").val(d+" ");updateLists({list:a.lists,outliners:a.outliners},false);updateGroups(a.groups,false);updateTagStatus();$("#diigobm-recommend-tag").find(".diigo-tag").length==0&&sendMessage({type:"getRecommendedTags"});buildTagCloud(a.myTagsWithCount);c.saved===false&&chrome.storage.local.get(null,function(e){if(e.researchMode===true){$("#top-bar").find(".focus-research-tip").show();fillReasearchModeData(e,c.mode)}})}
function updateTagStatus(){var a=$("#diigobm-tag-input"),c=ParseTags.parseTags(a.val(),true);$("#tag-cloud-container").find(".Diigo-Bookmark-Tag-item").each(function(){var d=$(this),e=d.text();$.inArray(e,c)!=-1?d.addClass("selected"):d.removeClass("selected")});$("#diigobm-recent-tag, #diigobm-recommend-tag, #diigobm-group-tag").find(".diigo-tag").each(function(){var d=$(this),e=d.text();$.inArray(e,c)!=-1?d.addClass("selected"):d.removeClass("selected")})}
function updateLists(a,c){$("#refresh-outliner").removeClass("processing");var d=a.list,e=a.outliners,g=$("#diigobm-list").find(".item-container");g.empty();if(e.length){$('<div class="menu-title">Outliners</div>').appendTo(g);forEach(e,function(b){var h=inOutliner(b.id)?b.title+" (added)":b.title;$('<div class="menu-item" data-id="'+b.id+'">'+h+"</div>").appendTo(g)})}if(d.length){$('<div class="menu-title">Lists</div>').appendTo(g);forEach(d,function(b){var h=inList(b.id)?b.title+" (added)":b.title;
$('<div class="menu-item" data-id="'+b.id+'">'+h+"</div>").appendTo(g)})}var f=$("#diigobm-list").find("select").empty().unbind().removeClass("processing");f.append(Utils.dom.buildOne("option",{value:0},["Add to an Outliner"]));f.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-2},["Create an Outliner..."])).appendTo(f);f.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));forEach(e,function(b){c?f.append(Utils.dom.buildOne("option",
{value:b.id},[b.title])):f.append(Utils.dom.buildOne("option",{value:b.id},[b.title+(inList(b.id)?" (added)":"")]))});f.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));if(d.length){f.append(Utils.dom.buildOne("option",{value:-8},["Add to a List"]));f.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));forEach(d,function(b){c?f.append(Utils.dom.buildOne("option",{value:b.id},[b.title])):f.append(Utils.dom.buildOne("option",{value:b.id},[b.title+(inList(b.id)?
" (added)":"")]))})}f.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-3},["Refresh"])).appendTo(f);f.change(function(){var b=f.val();if(b==-2){if(GlobalData.permissions.createOutliner===true){$("#diigobm-list-add").show();$("#diigobm-list").hide();$("#diigobm-list-addInput").focus()}else{$("#diigobm-list-add-tip").show();$("#diigobm-list").hide()}f.val(0);f.remvoeClass("selected")}else if(b==-3){$(this).addClass("processing");chrome.tabs.getSelected(null,
function(h){chrome.tabs.sendMessage(h.id,{name:"refreshMyStuff"})});f.val(-1)}});f.val(0).change()}
function updateGroups(a,c){$("#refresh-group").removeClass("processing");var d=a.filter(function(b){return b.access_mode<5}),e=a.filter(function(b){return b.access_mode>=5}),g=$("#diigobm-group").find(".item-container");g.empty();if(e.length){$('<div class="menu-title">Teams</div>').appendTo(g);forEach(e,function(b){var h=inGroup(b.name)?b.displayName+" (shared)":b.displayName;$('<div class="menu-item" data-id="'+b.name+'">'+h+"</div>").on("click",function(){var i=b.name;if(popCtx.groupTagsDict[i]!=
undefined)showTags("group",popCtx.groupTagsDict[i]);else{$("#diigobm-group-tag").show();sendMessage({type:"loadGroupTagsDictionary",groupName:i})}}).appendTo(g)})}if(d.length){$('<div class="menu-title">Groups</div>').appendTo(g);forEach(d,function(b){var h=inGroup(b.name)?b.displayName+" (shared)":b.displayName;$('<div class="menu-item" data-id="'+b.name+'">'+h+"</div>").on("click",function(){var i=b.name;if(popCtx.groupTagsDict[i]!=undefined)showTags("group",popCtx.groupTagsDict[i]);else{$("#diigobm-group-tag").show();
sendMessage({type:"loadGroupTagsDictionary",groupName:i})}}).appendTo(g)})}var f=$("#diigobm-group").find("select").empty().unbind().removeClass("processing");if(e.length>0){f.append(Utils.dom.buildOne("option",{value:0},["Share to a Team"]));f.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")]));forEach(e,function(b){c?f.append(Utils.dom.buildOne("option",{value:b.name},[b.displayName])):f.append(Utils.dom.buildOne("option",{value:b.name},[b.displayName+(inGroup(b.name)?" (shared)":
"")]))});f.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")]))}f.append(Utils.dom.buildOne("option",{value:0},["Share to a Group"]));f.append(Utils.dom.buildOne("option",{value:-1},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-2},["Create a Group..."])).appendTo(f);f.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")]));forEach(d,function(b){c?f.append(Utils.dom.buildOne("option",{value:b.name},[b.displayName])):f.append(Utils.dom.buildOne("option",
{value:b.name},[b.displayName+(inGroup(b.name)?" (shared)":"")]))});f.append(Utils.dom.buildOne("option",{value:-5},[Array(20).join("-")]));$(Utils.dom.buildOne("option",{value:-3},["Refresh"])).appendTo(f);f.change(function(){var b=f.val();if(b==-2){chrome.tabs.create({url:"https://groups.diigo.com/create"});f.val(-1)}else if(b==-3){$(this).addClass("processing");chrome.tabs.getSelected(null,function(h){chrome.tabs.sendMessage(h.id,{name:"refreshMyStuff"})});f.val(-1)}if(b!=0&&b!=-1&&b!=-2&&b!=-3){$("#diigosc-group-tag").show();
popCtx.isAnnotated&&$("#bottom").find("div:first-child").show();$("#Diigo-Bookmark-checkShareExisting").show();if(popCtx.groupTagsDict[b]!=undefined)showTags("group",popCtx.groupTagsDict[b]);else{$("#diigobm-group-tag").show();chrome.tabs.getSelected(null,function(h){chrome.tabs.sendMessage(h.id,{name:"loadGroupTagsDictionary",groupName:b})})}}});f.val(0).change()}
function fillReasearchModeData(a,c){var d=a.researchModeData;d._private===true||c==2?$("#op-private").prop("checked",true):$("#op-private").prop("checked",false);d.unread===true&&$("#op-readlater").prop("checked",true);d.cache&&d.cache===true&&$("#op-cache").prop("checked",true);$("#diigobm-des-input").val(d.description);var e=ParseTags.unparseTags(d.tags);$("#diigobm-tag-input").val(e);updateTagStatus();d.shareLists&&d.shareLists.length&&$("#diigobm-list").find("select").val(d.shareLists[0]);d.shareGroups&&
d.shareGroups.length&&$("#diigobm-group").find("select").val(d.shareGroups[0])}
function buildTagCloud(a){if(a.length==0){var c=document.getElementById("tag-cloud-container");a=document.createElement("div");a.id="no-tag";a.innerHTML="You haven't create any tags yet,:)";c.appendChild(a)}else if(!($("#tag-cloud-container").find("a").length>0)){var d=getTagScale(a);c=d.topTags;var e=d.maxCount;a=d.first;var g=d.second,f=d.third,b=c.length;d=document.createDocumentFragment();for(var h=0;h<b;h++){var i=document.createElement("a");i.className="Diigo-Bookmark-Tag-item";i.href="#";i.innerText=
c[h].name;var k=c[h].count;if(k==e){i.style.fontSize="20px";i.style.fontWeight="bold"}a.forEach(function(j){if(k==j){i.style.fontSize="18px";i.style.fontWeight="bold"}});g.forEach(function(j){if(k==j){i.style.fontSize="16px";i.style.fontWeight="bold"}});f.forEach(function(j){if(k==j){i.style.fontSize="16px";i.style.fontWeight="regular"}});d.appendChild(i)}c=document.getElementById("tag-cloud-container");c.appendChild(d);$("#tag-cloud-container").on("click","a",function(j){/Diigo\-Bookmark\-Tag\-item/.test(j.target.className)&&
toggleTag($(this).text())});updateTagStatus()}};
