var Bg=chrome.extension.getBackgroundPage(),Prefs=Bg.Prefs;function getSelectedTab(a){chrome.tabs.query({active:true,currentWindow:true},function(b){a(b[0])})}
function buildSelect(){for(var a=$("<select></select>"),b=48;b<91;b++)if(!(b>57&&b<65)){var c=String.fromCharCode(b);$("<option></option>").attr({value:c}).text(c).appendTo(a)}a.on("change",function(){var d=$(this).parents(".shortcut").attr("data-type"),e={};e["prefs.shortcut"+d+"Key"]=$(this).val();Prefs.set(e)});a.appendTo($(".shortcut"));$(".shortcut[data-type=Bookmark]").find("select").val(Prefs.get("prefs.shortcutBookmarkKey")||"Q");$(".shortcut[data-type=Annotate]").find("select").val(Prefs.get("prefs.shortcutAnnotateKey")||
"D");$(".shortcut[data-type=Readlater]").find("select").val(Prefs.get("prefs.shortcutReadlaterKey")||"R");$(".shortcut[data-type=AnnotateArticle]").find("select").val(Prefs.get("prefs.shortcutAnnotateArticleKey")||"T");$(".shortcut[data-type=AnnotatePDF]").find("select").val(Prefs.get("prefs.shortcutAnnotatePDFKey")||"P");$(".shortcut[data-type=AnnotateScreenshot]").find("select").val(Prefs.get("prefs.shortcutAnnotateScreenshotKey")||"S")}
function shortcutSwitchState(a){$("#check-shortcut-"+a).is(":checked")?$("#check-shortcut-"+a+"-ctrl,#check-shortcut-"+a+"-alt,#shortcut-"+a+" select").removeAttr("disabled"):$("#check-shortcut-"+a+"-ctrl,#check-shortcut-"+a+"-alt,#shortcut-"+a+" select").attr("disabled","true")}
function initFocusResearch(){chrome.storage.local.get(["researchMode","researchModeData"],function(a){if(a.researchMode==true){$("#check-focusResearch").prop("checked",true);$("#focus-research-options").show()}if(a.researchModeData){a=a.researchModeData;var b=ParseTags.unparseTags(a.tags||[]);$("#r-tag-input").val(b);if(a._private||Prefs.get("prefs.bookmark.privateByDefault")=="true")$("#f-private").prop("checked",true);a.unread&&$("#f-read-later").prop("checked",true);a.cache&&$("#f-cache").prop("checked",
true)}})}
function perfs2UI(){$("#check-bmPrivateAsDefault").attr({checked:Prefs.get("prefs.bookmark.privateByDefault")=="true"});$("#check-autoloadBookmarkStatus").attr({checked:Prefs.get("prefs.autoloadBookmarkStatus")=="true"});$("#check-autoload").attr({checked:Prefs.get("prefs.autoload")=="true"});$("#check-contextMenu").attr({checked:Prefs.get("prefs.contextMenu")=="true"});$("#check-comboSearch").attr({checked:Prefs.get("prefs.comboSearch")=="true"});$("#check-searcho").attr({checked:Prefs.get("prefs.SearchO")=="true"});
$("#check-autoshowicon").attr({checked:Prefs.get("prefs.autoShowHighlightIcon")=="true"});$("#check-autoImageClipper").attr({checked:Prefs.get("prefs.autoImageClipper")=="true"});$("#check-autoCloseReadLater").attr({checked:Prefs.get("prefs.autoCloseReadLater")=="true"});$("#check-shortcut-annotate").attr({checked:Prefs.get("prefs.shortcutAnnotate")=="true"});$("#check-shortcut-bookmark").attr({checked:Prefs.get("prefs.shortcutBookmark")=="true"});$("#check-shortcut-readlater").attr({checked:Prefs.get("prefs.shortcutReadlater")==
"true"});$("#check-showSearchResultDirectly").attr({checked:Prefs.get("prefs.directlyShowSearchResults")=="true"});$("#check-shortcut-annotate-ctrl").attr({checked:Prefs.get("prefs.shortcutAnnotateCtrl")=="true"});$("#check-shortcut-annotate-alt").attr({checked:Prefs.get("prefs.shortcutAnnotateAlt")=="true"});$("#shortcut-annotate select").val(Prefs.get("prefs.shortcutAnnotateKey"));$("#check-shortcut-bookmark-ctrl").attr({checked:Prefs.get("prefs.shortcutBookmarkCtrl")=="true"});$("#check-shortcut-bookmark-alt").attr({checked:Prefs.get("prefs.shortcutBookmarkAlt")==
"true"});$("#shortcut-bookmark select").val(Prefs.get("prefs.shortcutBookmarkKey"));$("#check-shortcut-a-article-ctrl").attr({checked:Prefs.get("prefs.shortcutAnnotateArticleCtrl")=="true"});$("#check-shortcut-a-article-alt").attr({checked:Prefs.get("prefs.shortcutAnnotateArticleAlt")=="true"});$("#check-shortcut-a-article").attr({checked:Prefs.get("prefs.shortcutAnnotateArticle")=="true"});$("#check-shortcut-a-pdf-ctrl").attr({checked:Prefs.get("prefs.shortcutAnnotatePDFCtrl")=="true"});$("#check-shortcut-a-pdf-alt").attr({checked:Prefs.get("prefs.shortcutAnnotatePDFAlt")==
"true"});$("#check-shortcut-a-pdf").attr({checked:Prefs.get("prefs.shortcutAnnotatePDF")=="true"});$("#check-shortcut-a-screenshot-ctrl").attr({checked:Prefs.get("prefs.shortcutAnnotateScreenshotCtrl")=="true"});$("#check-shortcut-a-screenshot-alt").attr({checked:Prefs.get("prefs.shortcutAnnotateScreenshotAlt")=="true"});$("#check-shortcut-a-screenshot").attr({checked:Prefs.get("prefs.shortcutAnnotateScreenshot")=="true"});$("#check-shortcut-readlater-ctrl").attr({checked:Prefs.get("prefs.shortcutReadlaterCtrl")==
"true"});$("#check-shortcut-readlater-alt").attr({checked:Prefs.get("prefs.shortcutReadlaterAlt")=="true"});$("#shortcut-readlater select").val(Prefs.get("prefs.shortcutReadlaterKey"));$("#check-showPdfButton").attr({checked:Prefs.get("prefs.showPdfButton")=="true"});shortcutSwitchState("bookmark");shortcutSwitchState("annotate");shortcutSwitchState("readlater");initFocusResearch()}var saveTimer=null;
function saveFocusResearchData(){saveTimer!==null&&clearTimeout(saveTimer);saveTimer=setTimeout(function(){var a=$("#r-tag-input").val();a=ParseTags.parseTags(a);var b=$("#f-private").prop("checked"),c=$("#f-read-later").prop("checked"),d=$("#f-cache").prop("checked");chrome.storage.local.set({researchModeData:{tags:a,_private:b,unread:c,cache:d}})},150)}
$("label input[data-pref]").on("change",function(){var a=$(this).attr("data-pref"),b=$(this).prop("checked"),c={};c[a]=b;Prefs.set(c);if(a=="prefs.autoloadBookmarkStatus"&&b==false){$("#check-autoload").prop("checked",false);Prefs.set({"prefs.autoload":false})}if(a=="prefs.autoload"&&b==true){$("#check-autoloadBookmarkStatus").prop("checked",true);Prefs.set({"prefs.autoloadBookmarkStatus":true})}if(a=="prefs.comboSearch"&&b==false){$("#check-showSearchResultDirectly").prop("checked",false);Prefs.set({"prefs.directlyShowSearchResults":false})}if(a==
"prefs.directlyShowSearchResults"&&b==true){$("#check-comboSearch").prop("checked",true);Prefs.set({"prefs.comboSearch":true})}a=="prefs.shortcutAnnotate"&&shortcutSwitchState("annotate");a=="prefs.shortcutBookmark"&&shortcutSwitchState("bookmark");a=="prefs.shortcutReadlater"&&shortcutSwitchState("readlater")});$("#check-focusResearch").on("change",function(){var a=$(this).prop("checked");chrome.storage.local.set({researchMode:a});a?$("#focus-research-options").show():$("#focus-research-options").hide()});
$("#focus-research-options").find("input").on("input",saveFocusResearchData).end().find("input[type=checkbox]").on("change",saveFocusResearchData);buildSelect();perfs2UI();
